### ISSUE TITLE
libFFT.so fails to load with Android 6 ApiLevel 23

### ISSUE THREAD

**Issue by vicktor** [iHealthLabs/Android-SDK#1]
logcat

12-10 21:04:12.396 30418-30418/com.example.sdk_demo E/AndroidRuntime: FATAL EXCEPTION: main
         Process: com.example.sdk_demo, PID: 30418
         java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.example.sdk_demo-1/lib/arm/libFFT.so: has text relocations
             at java.lang.Runtime.loadLibrary(Runtime.java:372)
             at java.lang.System.loadLibrary(System.java:1076)
             at com.houxiyang.guitar.Utils.TunnerThread.<clinit>(Unknown Source)
             at com.jiuan.android.sdk.bg.audio.BG1Control.start_new(Unknown Source)
             at com.example.sdk_demo.MainActivity.msgUserStatus(MainActivity.java:545)
             at com.jiuan.android.sdk.bg.observer.Subject_BG.notifyObserverUserStatus(Unknown Source)
             at com.jiuan.android.sdk.bg.audio.b.handleMessage(Unknown Source)
             at android.os.Handler.dispatchMessage(Handler.java:102)
             at android.os.Looper.loop(Looper.java:148)
             at android.app.ActivityThread.main(ActivityThread.java:5417)
             at java.lang.reflect.Method.invoke(Native Method)
             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ihealth-webmaster** [comment]
Thanks for your feedback
